[2023-09-21T09:00:32.359+0900] {processor.py:157} INFO - Started process (PID=21356) to work on /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:00:32.359+0900] {processor.py:829} INFO - Processing file /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-09-21T09:00:32.360+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:00:32.359+0900] {dagbag.py:539} INFO - Filling up the DagBag from /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:00:32.361+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:00:32.361+0900] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-09-21T09:00:32.361+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:00:32.361+0900] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-09-21T09:00:32.362+0900] {processor.py:841} WARNING - No viable dags retrieved from /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:00:32.367+0900] {processor.py:179} INFO - Processing /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.010 seconds
[2023-09-21T09:01:18.912+0900] {processor.py:157} INFO - Started process (PID=21543) to work on /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:01:18.913+0900] {processor.py:829} INFO - Processing file /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-09-21T09:01:18.914+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:01:18.914+0900] {dagbag.py:539} INFO - Filling up the DagBag from /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:01:18.916+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:01:18.916+0900] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-09-21T09:01:18.916+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:01:18.916+0900] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-09-21T09:01:18.916+0900] {processor.py:841} WARNING - No viable dags retrieved from /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:01:18.921+0900] {processor.py:179} INFO - Processing /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.011 seconds
[2023-09-21T09:02:03.183+0900] {processor.py:157} INFO - Started process (PID=21724) to work on /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:02:03.185+0900] {processor.py:829} INFO - Processing file /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-09-21T09:02:03.185+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:02:03.185+0900] {dagbag.py:539} INFO - Filling up the DagBag from /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:02:03.188+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:02:03.187+0900] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-09-21T09:02:03.188+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:02:03.188+0900] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-09-21T09:02:03.188+0900] {processor.py:841} WARNING - No viable dags retrieved from /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:02:03.194+0900] {processor.py:179} INFO - Processing /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.012 seconds
[2023-09-21T09:02:52.269+0900] {processor.py:157} INFO - Started process (PID=21921) to work on /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:02:52.271+0900] {processor.py:829} INFO - Processing file /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-09-21T09:02:52.271+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:02:52.271+0900] {dagbag.py:539} INFO - Filling up the DagBag from /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:02:52.273+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:02:52.273+0900] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-09-21T09:02:52.273+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:02:52.273+0900] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-09-21T09:02:52.273+0900] {processor.py:841} WARNING - No viable dags retrieved from /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:02:52.279+0900] {processor.py:179} INFO - Processing /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.012 seconds
[2023-09-21T09:03:37.118+0900] {processor.py:157} INFO - Started process (PID=22095) to work on /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:03:37.120+0900] {processor.py:829} INFO - Processing file /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-09-21T09:03:37.121+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:03:37.121+0900] {dagbag.py:539} INFO - Filling up the DagBag from /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:03:37.123+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:03:37.122+0900] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-09-21T09:03:37.123+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:03:37.123+0900] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-09-21T09:03:37.123+0900] {processor.py:841} WARNING - No viable dags retrieved from /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:03:37.128+0900] {processor.py:179} INFO - Processing /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.012 seconds
[2023-09-21T09:04:26.903+0900] {processor.py:157} INFO - Started process (PID=22297) to work on /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:04:26.903+0900] {processor.py:829} INFO - Processing file /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-09-21T09:04:26.904+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:04:26.904+0900] {dagbag.py:539} INFO - Filling up the DagBag from /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:04:26.906+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:04:26.905+0900] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-09-21T09:04:26.906+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:04:26.906+0900] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-09-21T09:04:26.906+0900] {processor.py:841} WARNING - No viable dags retrieved from /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:04:26.911+0900] {processor.py:179} INFO - Processing /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.011 seconds
[2023-09-21T09:05:16.421+0900] {processor.py:157} INFO - Started process (PID=22497) to work on /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:05:16.423+0900] {processor.py:829} INFO - Processing file /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-09-21T09:05:16.424+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:05:16.424+0900] {dagbag.py:539} INFO - Filling up the DagBag from /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:05:16.426+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:05:16.425+0900] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-09-21T09:05:16.426+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:05:16.426+0900] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-09-21T09:05:16.426+0900] {processor.py:841} WARNING - No viable dags retrieved from /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:05:16.431+0900] {processor.py:179} INFO - Processing /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.012 seconds
[2023-09-21T09:06:02.509+0900] {processor.py:157} INFO - Started process (PID=22692) to work on /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:06:02.511+0900] {processor.py:829} INFO - Processing file /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-09-21T09:06:02.512+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:06:02.512+0900] {dagbag.py:539} INFO - Filling up the DagBag from /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:06:02.514+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:06:02.513+0900] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-09-21T09:06:02.514+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:06:02.514+0900] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-09-21T09:06:02.514+0900] {processor.py:841} WARNING - No viable dags retrieved from /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:06:02.521+0900] {processor.py:179} INFO - Processing /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.015 seconds
[2023-09-21T09:06:45.313+0900] {processor.py:157} INFO - Started process (PID=22867) to work on /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:06:45.313+0900] {processor.py:829} INFO - Processing file /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-09-21T09:06:45.314+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:06:45.314+0900] {dagbag.py:539} INFO - Filling up the DagBag from /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:06:45.316+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:06:45.315+0900] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-09-21T09:06:45.316+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:06:45.316+0900] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-09-21T09:06:45.316+0900] {processor.py:841} WARNING - No viable dags retrieved from /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:06:45.321+0900] {processor.py:179} INFO - Processing /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.011 seconds
[2023-09-21T09:07:31.441+0900] {processor.py:157} INFO - Started process (PID=23055) to work on /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:07:31.443+0900] {processor.py:829} INFO - Processing file /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-09-21T09:07:31.443+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:07:31.443+0900] {dagbag.py:539} INFO - Filling up the DagBag from /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:07:31.445+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:07:31.445+0900] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-09-21T09:07:31.445+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:07:31.445+0900] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-09-21T09:07:31.445+0900] {processor.py:841} WARNING - No viable dags retrieved from /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:07:31.451+0900] {processor.py:179} INFO - Processing /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.012 seconds
[2023-09-21T09:08:15.370+0900] {processor.py:157} INFO - Started process (PID=23231) to work on /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:08:15.372+0900] {processor.py:829} INFO - Processing file /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-09-21T09:08:15.373+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:08:15.372+0900] {dagbag.py:539} INFO - Filling up the DagBag from /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:08:15.375+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:08:15.374+0900] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-09-21T09:08:15.375+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:08:15.375+0900] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-09-21T09:08:15.375+0900] {processor.py:841} WARNING - No viable dags retrieved from /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:08:15.380+0900] {processor.py:179} INFO - Processing /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.012 seconds
[2023-09-21T09:08:58.193+0900] {processor.py:157} INFO - Started process (PID=23405) to work on /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:08:58.194+0900] {processor.py:829} INFO - Processing file /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-09-21T09:08:58.194+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:08:58.194+0900] {dagbag.py:539} INFO - Filling up the DagBag from /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:08:58.196+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:08:58.196+0900] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-09-21T09:08:58.196+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:08:58.196+0900] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-09-21T09:08:58.196+0900] {processor.py:841} WARNING - No viable dags retrieved from /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:08:58.203+0900] {processor.py:179} INFO - Processing /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.012 seconds
[2023-09-21T09:09:42.732+0900] {processor.py:157} INFO - Started process (PID=23586) to work on /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:09:42.734+0900] {processor.py:829} INFO - Processing file /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-09-21T09:09:42.735+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:09:42.735+0900] {dagbag.py:539} INFO - Filling up the DagBag from /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:09:42.737+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:09:42.736+0900] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-09-21T09:09:42.737+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:09:42.737+0900] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-09-21T09:09:42.737+0900] {processor.py:841} WARNING - No viable dags retrieved from /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:09:42.743+0900] {processor.py:179} INFO - Processing /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.012 seconds
[2023-09-21T09:10:27.809+0900] {processor.py:157} INFO - Started process (PID=23776) to work on /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:10:27.811+0900] {processor.py:829} INFO - Processing file /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-09-21T09:10:27.811+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:10:27.811+0900] {dagbag.py:539} INFO - Filling up the DagBag from /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:10:27.813+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:10:27.813+0900] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-09-21T09:10:27.813+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:10:27.813+0900] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-09-21T09:10:27.814+0900] {processor.py:841} WARNING - No viable dags retrieved from /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:10:27.819+0900] {processor.py:179} INFO - Processing /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.013 seconds
[2023-09-21T09:11:12.202+0900] {processor.py:157} INFO - Started process (PID=23958) to work on /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:11:12.203+0900] {processor.py:829} INFO - Processing file /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-09-21T09:11:12.204+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:11:12.204+0900] {dagbag.py:539} INFO - Filling up the DagBag from /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:11:12.206+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:11:12.205+0900] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-09-21T09:11:12.206+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:11:12.206+0900] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-09-21T09:11:12.206+0900] {processor.py:841} WARNING - No viable dags retrieved from /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:11:12.211+0900] {processor.py:179} INFO - Processing /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.011 seconds
[2023-09-21T09:11:59.461+0900] {processor.py:157} INFO - Started process (PID=24147) to work on /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:11:59.462+0900] {processor.py:829} INFO - Processing file /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-09-21T09:11:59.463+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:11:59.462+0900] {dagbag.py:539} INFO - Filling up the DagBag from /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:11:59.465+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:11:59.464+0900] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-09-21T09:11:59.465+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:11:59.465+0900] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-09-21T09:11:59.465+0900] {processor.py:841} WARNING - No viable dags retrieved from /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:11:59.470+0900] {processor.py:179} INFO - Processing /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.011 seconds
[2023-09-21T09:12:42.561+0900] {processor.py:157} INFO - Started process (PID=24322) to work on /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:12:42.563+0900] {processor.py:829} INFO - Processing file /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-09-21T09:12:42.563+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:12:42.563+0900] {dagbag.py:539} INFO - Filling up the DagBag from /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:12:42.565+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:12:42.565+0900] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-09-21T09:12:42.565+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:12:42.565+0900] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-09-21T09:12:42.565+0900] {processor.py:841} WARNING - No viable dags retrieved from /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:12:42.571+0900] {processor.py:179} INFO - Processing /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.012 seconds
[2023-09-21T09:13:27.671+0900] {processor.py:157} INFO - Started process (PID=24501) to work on /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:13:27.673+0900] {processor.py:829} INFO - Processing file /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-09-21T09:13:27.673+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:13:27.673+0900] {dagbag.py:539} INFO - Filling up the DagBag from /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:13:27.675+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:13:27.675+0900] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-09-21T09:13:27.675+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:13:27.675+0900] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-09-21T09:13:27.675+0900] {processor.py:841} WARNING - No viable dags retrieved from /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:13:27.681+0900] {processor.py:179} INFO - Processing /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.012 seconds
[2023-09-21T09:14:14.951+0900] {processor.py:157} INFO - Started process (PID=24690) to work on /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:14:14.952+0900] {processor.py:829} INFO - Processing file /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-09-21T09:14:14.952+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:14:14.952+0900] {dagbag.py:539} INFO - Filling up the DagBag from /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:14:14.955+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:14:14.954+0900] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-09-21T09:14:14.955+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:14:14.955+0900] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-09-21T09:14:14.955+0900] {processor.py:841} WARNING - No viable dags retrieved from /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:14:14.961+0900] {processor.py:179} INFO - Processing /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.012 seconds
[2023-09-21T09:15:04.051+0900] {processor.py:157} INFO - Started process (PID=24885) to work on /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:15:04.053+0900] {processor.py:829} INFO - Processing file /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-09-21T09:15:04.054+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:15:04.054+0900] {dagbag.py:539} INFO - Filling up the DagBag from /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:15:04.056+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:15:04.055+0900] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-09-21T09:15:04.056+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:15:04.056+0900] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-09-21T09:15:04.056+0900] {processor.py:841} WARNING - No viable dags retrieved from /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:15:04.061+0900] {processor.py:179} INFO - Processing /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.012 seconds
[2023-09-21T09:15:50.301+0900] {processor.py:157} INFO - Started process (PID=25086) to work on /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:15:50.303+0900] {processor.py:829} INFO - Processing file /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-09-21T09:15:50.304+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:15:50.304+0900] {dagbag.py:539} INFO - Filling up the DagBag from /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:15:50.305+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:15:50.305+0900] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-09-21T09:15:50.306+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:15:50.306+0900] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-09-21T09:15:50.306+0900] {processor.py:841} WARNING - No viable dags retrieved from /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:15:50.311+0900] {processor.py:179} INFO - Processing /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.012 seconds
[2023-09-21T09:16:35.251+0900] {processor.py:157} INFO - Started process (PID=25268) to work on /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:16:35.253+0900] {processor.py:829} INFO - Processing file /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-09-21T09:16:35.254+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:16:35.254+0900] {dagbag.py:539} INFO - Filling up the DagBag from /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:16:35.255+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:16:35.255+0900] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-09-21T09:16:35.256+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:16:35.256+0900] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-09-21T09:16:35.256+0900] {processor.py:841} WARNING - No viable dags retrieved from /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:16:35.261+0900] {processor.py:179} INFO - Processing /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.012 seconds
[2023-09-21T09:17:17.663+0900] {processor.py:157} INFO - Started process (PID=25457) to work on /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:17:17.665+0900] {processor.py:829} INFO - Processing file /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-09-21T09:17:17.665+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:17:17.665+0900] {dagbag.py:539} INFO - Filling up the DagBag from /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:17:17.667+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:17:17.667+0900] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-09-21T09:17:17.667+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:17:17.667+0900] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-09-21T09:17:17.667+0900] {processor.py:841} WARNING - No viable dags retrieved from /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:17:17.673+0900] {processor.py:179} INFO - Processing /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.012 seconds
[2023-09-21T09:18:08.752+0900] {processor.py:157} INFO - Started process (PID=25756) to work on /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:18:08.753+0900] {processor.py:829} INFO - Processing file /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-09-21T09:18:08.754+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:18:08.753+0900] {dagbag.py:539} INFO - Filling up the DagBag from /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:18:08.755+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:18:08.755+0900] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-09-21T09:18:08.755+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:18:08.755+0900] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-09-21T09:18:08.755+0900] {processor.py:841} WARNING - No viable dags retrieved from /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:18:08.761+0900] {processor.py:179} INFO - Processing /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.011 seconds
[2023-09-21T09:18:52.277+0900] {processor.py:157} INFO - Started process (PID=25972) to work on /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:18:52.278+0900] {processor.py:829} INFO - Processing file /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-09-21T09:18:52.279+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:18:52.278+0900] {dagbag.py:539} INFO - Filling up the DagBag from /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:18:52.280+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:18:52.280+0900] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-09-21T09:18:52.280+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:18:52.280+0900] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-09-21T09:18:52.281+0900] {processor.py:841} WARNING - No viable dags retrieved from /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:18:52.286+0900] {processor.py:179} INFO - Processing /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.011 seconds
[2023-09-21T09:19:47.668+0900] {processor.py:157} INFO - Started process (PID=26195) to work on /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:19:47.670+0900] {processor.py:829} INFO - Processing file /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-09-21T09:19:47.671+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:19:47.671+0900] {dagbag.py:539} INFO - Filling up the DagBag from /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:19:47.673+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:19:47.672+0900] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-09-21T09:19:47.673+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:19:47.673+0900] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-09-21T09:19:47.673+0900] {processor.py:841} WARNING - No viable dags retrieved from /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:19:47.679+0900] {processor.py:179} INFO - Processing /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.013 seconds
[2023-09-21T09:20:36.077+0900] {processor.py:157} INFO - Started process (PID=26620) to work on /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:20:36.078+0900] {processor.py:829} INFO - Processing file /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-09-21T09:20:36.079+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:20:36.078+0900] {dagbag.py:539} INFO - Filling up the DagBag from /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:20:36.080+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:20:36.080+0900] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-09-21T09:20:36.081+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:20:36.081+0900] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-09-21T09:20:36.081+0900] {processor.py:841} WARNING - No viable dags retrieved from /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:20:36.086+0900] {processor.py:179} INFO - Processing /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.010 seconds
[2023-09-21T09:21:23.435+0900] {processor.py:157} INFO - Started process (PID=26919) to work on /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:21:23.436+0900] {processor.py:829} INFO - Processing file /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-09-21T09:21:23.437+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:21:23.437+0900] {dagbag.py:539} INFO - Filling up the DagBag from /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:21:23.439+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:21:23.439+0900] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-09-21T09:21:23.439+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:21:23.439+0900] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-09-21T09:21:23.439+0900] {processor.py:841} WARNING - No viable dags retrieved from /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:21:23.444+0900] {processor.py:179} INFO - Processing /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.010 seconds
[2023-09-21T09:22:07.290+0900] {processor.py:157} INFO - Started process (PID=27094) to work on /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:22:07.290+0900] {processor.py:829} INFO - Processing file /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-09-21T09:22:07.291+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:22:07.291+0900] {dagbag.py:539} INFO - Filling up the DagBag from /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:22:07.293+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:22:07.292+0900] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-09-21T09:22:07.293+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:22:07.293+0900] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-09-21T09:22:07.293+0900] {processor.py:841} WARNING - No viable dags retrieved from /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:22:07.298+0900] {processor.py:179} INFO - Processing /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.010 seconds
[2023-09-21T09:22:58.841+0900] {processor.py:157} INFO - Started process (PID=27302) to work on /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:22:58.843+0900] {processor.py:829} INFO - Processing file /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-09-21T09:22:58.843+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:22:58.843+0900] {dagbag.py:539} INFO - Filling up the DagBag from /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:22:58.845+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:22:58.845+0900] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-09-21T09:22:58.845+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:22:58.845+0900] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-09-21T09:22:58.845+0900] {processor.py:841} WARNING - No viable dags retrieved from /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:22:58.851+0900] {processor.py:179} INFO - Processing /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.012 seconds
[2023-09-21T09:23:46.530+0900] {processor.py:157} INFO - Started process (PID=27492) to work on /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:23:46.532+0900] {processor.py:829} INFO - Processing file /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-09-21T09:23:46.533+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:23:46.533+0900] {dagbag.py:539} INFO - Filling up the DagBag from /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:23:46.535+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:23:46.534+0900] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-09-21T09:23:46.535+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:23:46.535+0900] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-09-21T09:23:46.535+0900] {processor.py:841} WARNING - No viable dags retrieved from /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:23:46.541+0900] {processor.py:179} INFO - Processing /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.012 seconds
[2023-09-21T09:24:35.963+0900] {processor.py:157} INFO - Started process (PID=27695) to work on /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:24:35.965+0900] {processor.py:829} INFO - Processing file /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-09-21T09:24:35.965+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:24:35.965+0900] {dagbag.py:539} INFO - Filling up the DagBag from /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:24:35.967+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:24:35.967+0900] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-09-21T09:24:35.967+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:24:35.967+0900] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-09-21T09:24:35.967+0900] {processor.py:841} WARNING - No viable dags retrieved from /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:24:35.973+0900] {processor.py:179} INFO - Processing /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.012 seconds
[2023-09-21T09:25:22.086+0900] {processor.py:157} INFO - Started process (PID=27877) to work on /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:25:22.088+0900] {processor.py:829} INFO - Processing file /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-09-21T09:25:22.089+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:25:22.089+0900] {dagbag.py:539} INFO - Filling up the DagBag from /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:25:22.091+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:25:22.090+0900] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-09-21T09:25:22.091+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:25:22.091+0900] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-09-21T09:25:22.091+0900] {processor.py:841} WARNING - No viable dags retrieved from /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:25:22.096+0900] {processor.py:179} INFO - Processing /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.012 seconds
[2023-09-21T09:26:15.463+0900] {processor.py:157} INFO - Started process (PID=28104) to work on /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:26:15.464+0900] {processor.py:829} INFO - Processing file /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-09-21T09:26:15.464+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:26:15.464+0900] {dagbag.py:539} INFO - Filling up the DagBag from /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:26:15.466+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:26:15.466+0900] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-09-21T09:26:15.466+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:26:15.466+0900] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-09-21T09:26:15.466+0900] {processor.py:841} WARNING - No viable dags retrieved from /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:26:15.472+0900] {processor.py:179} INFO - Processing /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.011 seconds
[2023-09-21T09:27:04.570+0900] {processor.py:157} INFO - Started process (PID=28305) to work on /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:27:04.572+0900] {processor.py:829} INFO - Processing file /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-09-21T09:27:04.573+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:27:04.573+0900] {dagbag.py:539} INFO - Filling up the DagBag from /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:27:04.574+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:27:04.574+0900] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-09-21T09:27:04.575+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:27:04.575+0900] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-09-21T09:27:04.575+0900] {processor.py:841} WARNING - No viable dags retrieved from /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:27:04.580+0900] {processor.py:179} INFO - Processing /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.012 seconds
[2023-09-21T09:27:49.672+0900] {processor.py:157} INFO - Started process (PID=28489) to work on /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:27:49.673+0900] {processor.py:829} INFO - Processing file /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-09-21T09:27:49.673+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:27:49.673+0900] {dagbag.py:539} INFO - Filling up the DagBag from /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:27:49.675+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:27:49.675+0900] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-09-21T09:27:49.675+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:27:49.675+0900] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-09-21T09:27:49.675+0900] {processor.py:841} WARNING - No viable dags retrieved from /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:27:49.681+0900] {processor.py:179} INFO - Processing /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.011 seconds
[2023-09-21T09:28:34.637+0900] {processor.py:157} INFO - Started process (PID=28671) to work on /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:28:34.638+0900] {processor.py:829} INFO - Processing file /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-09-21T09:28:34.639+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:28:34.639+0900] {dagbag.py:539} INFO - Filling up the DagBag from /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:28:34.641+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:28:34.640+0900] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-09-21T09:28:34.641+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:28:34.641+0900] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-09-21T09:28:34.641+0900] {processor.py:841} WARNING - No viable dags retrieved from /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:28:34.646+0900] {processor.py:179} INFO - Processing /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.010 seconds
[2023-09-21T09:29:17.065+0900] {processor.py:157} INFO - Started process (PID=28843) to work on /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:29:17.066+0900] {processor.py:829} INFO - Processing file /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-09-21T09:29:17.066+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:29:17.066+0900] {dagbag.py:539} INFO - Filling up the DagBag from /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:29:17.068+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:29:17.068+0900] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-09-21T09:29:17.068+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:29:17.068+0900] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-09-21T09:29:17.068+0900] {processor.py:841} WARNING - No viable dags retrieved from /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:29:17.074+0900] {processor.py:179} INFO - Processing /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.011 seconds
[2023-09-21T09:30:06.247+0900] {processor.py:157} INFO - Started process (PID=29038) to work on /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:30:06.250+0900] {processor.py:829} INFO - Processing file /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-09-21T09:30:06.250+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:30:06.250+0900] {dagbag.py:539} INFO - Filling up the DagBag from /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:30:06.252+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:30:06.252+0900] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-09-21T09:30:06.252+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:30:06.252+0900] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-09-21T09:30:06.252+0900] {processor.py:841} WARNING - No viable dags retrieved from /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:30:06.258+0900] {processor.py:179} INFO - Processing /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.012 seconds
[2023-09-21T09:30:50.382+0900] {processor.py:157} INFO - Started process (PID=29231) to work on /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:30:50.384+0900] {processor.py:829} INFO - Processing file /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-09-21T09:30:50.385+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:30:50.385+0900] {dagbag.py:539} INFO - Filling up the DagBag from /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:30:50.387+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:30:50.386+0900] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-09-21T09:30:50.387+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:30:50.387+0900] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-09-21T09:30:50.387+0900] {processor.py:841} WARNING - No viable dags retrieved from /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:30:50.392+0900] {processor.py:179} INFO - Processing /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.012 seconds
[2023-09-21T09:31:39.475+0900] {processor.py:157} INFO - Started process (PID=29428) to work on /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:31:39.475+0900] {processor.py:829} INFO - Processing file /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-09-21T09:31:39.476+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:31:39.476+0900] {dagbag.py:539} INFO - Filling up the DagBag from /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:31:39.478+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:31:39.478+0900] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-09-21T09:31:39.478+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:31:39.478+0900] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-09-21T09:31:39.478+0900] {processor.py:841} WARNING - No viable dags retrieved from /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:31:39.484+0900] {processor.py:179} INFO - Processing /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.011 seconds
[2023-09-21T09:32:23.999+0900] {processor.py:157} INFO - Started process (PID=29601) to work on /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:32:24.001+0900] {processor.py:829} INFO - Processing file /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-09-21T09:32:24.002+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:32:24.002+0900] {dagbag.py:539} INFO - Filling up the DagBag from /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:32:24.004+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:32:24.003+0900] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-09-21T09:32:24.004+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:32:24.004+0900] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-09-21T09:32:24.004+0900] {processor.py:841} WARNING - No viable dags retrieved from /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:32:24.009+0900] {processor.py:179} INFO - Processing /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.012 seconds
[2023-09-21T09:33:10.833+0900] {processor.py:157} INFO - Started process (PID=29790) to work on /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:33:10.836+0900] {processor.py:829} INFO - Processing file /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-09-21T09:33:10.836+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:33:10.836+0900] {dagbag.py:539} INFO - Filling up the DagBag from /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:33:10.838+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:33:10.838+0900] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-09-21T09:33:10.839+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:33:10.838+0900] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-09-21T09:33:10.839+0900] {processor.py:841} WARNING - No viable dags retrieved from /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:33:10.844+0900] {processor.py:179} INFO - Processing /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.013 seconds
[2023-09-21T09:33:58.212+0900] {processor.py:157} INFO - Started process (PID=29990) to work on /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:33:58.214+0900] {processor.py:829} INFO - Processing file /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-09-21T09:33:58.215+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:33:58.214+0900] {dagbag.py:539} INFO - Filling up the DagBag from /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:33:58.217+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:33:58.216+0900] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-09-21T09:33:58.217+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:33:58.217+0900] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-09-21T09:33:58.217+0900] {processor.py:841} WARNING - No viable dags retrieved from /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:33:58.223+0900] {processor.py:179} INFO - Processing /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.012 seconds
[2023-09-21T09:34:54.716+0900] {processor.py:157} INFO - Started process (PID=30215) to work on /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:34:54.718+0900] {processor.py:829} INFO - Processing file /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-09-21T09:34:54.719+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:34:54.718+0900] {dagbag.py:539} INFO - Filling up the DagBag from /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:34:54.721+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:34:54.720+0900] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-09-21T09:34:54.721+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:34:54.721+0900] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-09-21T09:34:54.721+0900] {processor.py:841} WARNING - No viable dags retrieved from /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:34:54.727+0900] {processor.py:179} INFO - Processing /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.014 seconds
[2023-09-21T09:35:38.976+0900] {processor.py:157} INFO - Started process (PID=30408) to work on /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:35:38.978+0900] {processor.py:829} INFO - Processing file /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-09-21T09:35:38.979+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:35:38.978+0900] {dagbag.py:539} INFO - Filling up the DagBag from /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:35:38.980+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:35:38.980+0900] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-09-21T09:35:38.981+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:35:38.980+0900] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-09-21T09:35:38.981+0900] {processor.py:841} WARNING - No viable dags retrieved from /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:35:38.986+0900] {processor.py:179} INFO - Processing /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.012 seconds
[2023-09-21T09:36:26.628+0900] {processor.py:157} INFO - Started process (PID=30595) to work on /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:36:26.630+0900] {processor.py:829} INFO - Processing file /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-09-21T09:36:26.630+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:36:26.630+0900] {dagbag.py:539} INFO - Filling up the DagBag from /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:36:26.632+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:36:26.632+0900] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-09-21T09:36:26.632+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:36:26.632+0900] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-09-21T09:36:26.632+0900] {processor.py:841} WARNING - No viable dags retrieved from /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:36:26.638+0900] {processor.py:179} INFO - Processing /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.012 seconds
[2023-09-21T09:37:18.596+0900] {processor.py:157} INFO - Started process (PID=30874) to work on /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:37:18.599+0900] {processor.py:829} INFO - Processing file /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-09-21T09:37:18.599+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:37:18.599+0900] {dagbag.py:539} INFO - Filling up the DagBag from /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:37:18.601+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:37:18.601+0900] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-09-21T09:37:18.601+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:37:18.601+0900] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-09-21T09:37:18.601+0900] {processor.py:841} WARNING - No viable dags retrieved from /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:37:18.607+0900] {processor.py:179} INFO - Processing /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.012 seconds
[2023-09-21T09:38:04.516+0900] {processor.py:157} INFO - Started process (PID=31063) to work on /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:38:04.517+0900] {processor.py:829} INFO - Processing file /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-09-21T09:38:04.518+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:38:04.518+0900] {dagbag.py:539} INFO - Filling up the DagBag from /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:38:04.520+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:38:04.519+0900] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-09-21T09:38:04.520+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:38:04.520+0900] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-09-21T09:38:04.520+0900] {processor.py:841} WARNING - No viable dags retrieved from /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:38:04.525+0900] {processor.py:179} INFO - Processing /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.011 seconds
[2023-09-21T09:38:59.649+0900] {processor.py:157} INFO - Started process (PID=31285) to work on /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:38:59.651+0900] {processor.py:829} INFO - Processing file /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-09-21T09:38:59.652+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:38:59.652+0900] {dagbag.py:539} INFO - Filling up the DagBag from /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:38:59.654+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:38:59.653+0900] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-09-21T09:38:59.654+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:38:59.654+0900] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-09-21T09:38:59.654+0900] {processor.py:841} WARNING - No viable dags retrieved from /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:38:59.659+0900] {processor.py:179} INFO - Processing /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.012 seconds
[2023-09-21T09:39:48.745+0900] {processor.py:157} INFO - Started process (PID=31483) to work on /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:39:48.747+0900] {processor.py:829} INFO - Processing file /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-09-21T09:39:48.748+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:39:48.748+0900] {dagbag.py:539} INFO - Filling up the DagBag from /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:39:48.750+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:39:48.750+0900] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-09-21T09:39:48.750+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:39:48.750+0900] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-09-21T09:39:48.750+0900] {processor.py:841} WARNING - No viable dags retrieved from /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:39:48.756+0900] {processor.py:179} INFO - Processing /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.013 seconds
[2023-09-21T09:40:31.569+0900] {processor.py:157} INFO - Started process (PID=31670) to work on /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:40:31.572+0900] {processor.py:829} INFO - Processing file /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-09-21T09:40:31.572+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:40:31.572+0900] {dagbag.py:539} INFO - Filling up the DagBag from /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:40:31.574+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:40:31.574+0900] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-09-21T09:40:31.574+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:40:31.574+0900] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-09-21T09:40:31.574+0900] {processor.py:841} WARNING - No viable dags retrieved from /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:40:31.579+0900] {processor.py:179} INFO - Processing /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.012 seconds
[2023-09-21T09:41:14.948+0900] {processor.py:157} INFO - Started process (PID=31844) to work on /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:41:14.951+0900] {processor.py:829} INFO - Processing file /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-09-21T09:41:14.951+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:41:14.951+0900] {dagbag.py:539} INFO - Filling up the DagBag from /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:41:14.953+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:41:14.953+0900] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-09-21T09:41:14.953+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:41:14.953+0900] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-09-21T09:41:14.953+0900] {processor.py:841} WARNING - No viable dags retrieved from /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:41:14.958+0900] {processor.py:179} INFO - Processing /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.012 seconds
[2023-09-21T09:42:04.787+0900] {processor.py:157} INFO - Started process (PID=32040) to work on /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:42:04.788+0900] {processor.py:829} INFO - Processing file /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-09-21T09:42:04.788+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:42:04.788+0900] {dagbag.py:539} INFO - Filling up the DagBag from /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:42:04.790+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:42:04.790+0900] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-09-21T09:42:04.790+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:42:04.790+0900] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-09-21T09:42:04.790+0900] {processor.py:841} WARNING - No viable dags retrieved from /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:42:04.796+0900] {processor.py:179} INFO - Processing /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.011 seconds
[2023-09-21T09:42:51.963+0900] {processor.py:157} INFO - Started process (PID=32228) to work on /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:42:51.965+0900] {processor.py:829} INFO - Processing file /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-09-21T09:42:51.966+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:42:51.966+0900] {dagbag.py:539} INFO - Filling up the DagBag from /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:42:51.968+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:42:51.968+0900] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-09-21T09:42:51.969+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:42:51.969+0900] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-09-21T09:42:51.969+0900] {processor.py:841} WARNING - No viable dags retrieved from /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:42:51.975+0900] {processor.py:179} INFO - Processing /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.013 seconds
[2023-09-21T09:43:41.665+0900] {processor.py:157} INFO - Started process (PID=32432) to work on /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:43:41.667+0900] {processor.py:829} INFO - Processing file /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-09-21T09:43:41.668+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:43:41.668+0900] {dagbag.py:539} INFO - Filling up the DagBag from /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:43:41.670+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:43:41.669+0900] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-09-21T09:43:41.670+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:43:41.670+0900] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-09-21T09:43:41.670+0900] {processor.py:841} WARNING - No viable dags retrieved from /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:43:41.675+0900] {processor.py:179} INFO - Processing /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.012 seconds
[2023-09-21T09:44:25.931+0900] {processor.py:157} INFO - Started process (PID=32605) to work on /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:44:25.933+0900] {processor.py:829} INFO - Processing file /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-09-21T09:44:25.934+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:44:25.934+0900] {dagbag.py:539} INFO - Filling up the DagBag from /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:44:25.936+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:44:25.935+0900] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-09-21T09:44:25.936+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:44:25.936+0900] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-09-21T09:44:25.936+0900] {processor.py:841} WARNING - No viable dags retrieved from /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:44:25.941+0900] {processor.py:179} INFO - Processing /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.012 seconds
[2023-09-21T09:45:10.180+0900] {processor.py:157} INFO - Started process (PID=318) to work on /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:45:10.182+0900] {processor.py:829} INFO - Processing file /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-09-21T09:45:10.183+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:45:10.183+0900] {dagbag.py:539} INFO - Filling up the DagBag from /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:45:10.185+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:45:10.184+0900] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-09-21T09:45:10.185+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:45:10.185+0900] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-09-21T09:45:10.185+0900] {processor.py:841} WARNING - No viable dags retrieved from /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:45:10.190+0900] {processor.py:179} INFO - Processing /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.012 seconds
[2023-09-21T09:45:56.999+0900] {processor.py:157} INFO - Started process (PID=520) to work on /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:45:57.001+0900] {processor.py:829} INFO - Processing file /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-09-21T09:45:57.002+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:45:57.001+0900] {dagbag.py:539} INFO - Filling up the DagBag from /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:45:57.003+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:45:57.003+0900] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-09-21T09:45:57.003+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:45:57.003+0900] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-09-21T09:45:57.004+0900] {processor.py:841} WARNING - No viable dags retrieved from /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:45:57.009+0900] {processor.py:179} INFO - Processing /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.012 seconds
[2023-09-21T09:46:43.216+0900] {processor.py:157} INFO - Started process (PID=705) to work on /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:46:43.218+0900] {processor.py:829} INFO - Processing file /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-09-21T09:46:43.218+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:46:43.218+0900] {dagbag.py:539} INFO - Filling up the DagBag from /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:46:43.220+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:46:43.220+0900] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-09-21T09:46:43.220+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:46:43.220+0900] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-09-21T09:46:43.220+0900] {processor.py:841} WARNING - No viable dags retrieved from /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:46:43.226+0900] {processor.py:179} INFO - Processing /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.012 seconds
[2023-09-21T09:47:34.369+0900] {processor.py:157} INFO - Started process (PID=909) to work on /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:47:34.370+0900] {processor.py:829} INFO - Processing file /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-09-21T09:47:34.371+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:47:34.371+0900] {dagbag.py:539} INFO - Filling up the DagBag from /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:47:34.373+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:47:34.373+0900] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-09-21T09:47:34.373+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:47:34.373+0900] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-09-21T09:47:34.373+0900] {processor.py:841} WARNING - No viable dags retrieved from /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:47:34.379+0900] {processor.py:179} INFO - Processing /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.011 seconds
[2023-09-21T09:48:19.758+0900] {processor.py:157} INFO - Started process (PID=1095) to work on /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:48:19.760+0900] {processor.py:829} INFO - Processing file /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-09-21T09:48:19.761+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:48:19.760+0900] {dagbag.py:539} INFO - Filling up the DagBag from /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:48:19.762+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:48:19.762+0900] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-09-21T09:48:19.762+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:48:19.762+0900] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-09-21T09:48:19.763+0900] {processor.py:841} WARNING - No viable dags retrieved from /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:48:19.768+0900] {processor.py:179} INFO - Processing /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.012 seconds
[2023-09-21T09:49:10.434+0900] {processor.py:157} INFO - Started process (PID=1292) to work on /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:49:10.436+0900] {processor.py:829} INFO - Processing file /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-09-21T09:49:10.437+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:49:10.436+0900] {dagbag.py:539} INFO - Filling up the DagBag from /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:49:10.438+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:49:10.438+0900] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-09-21T09:49:10.438+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:49:10.438+0900] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-09-21T09:49:10.439+0900] {processor.py:841} WARNING - No viable dags retrieved from /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:49:10.444+0900] {processor.py:179} INFO - Processing /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.012 seconds
[2023-09-21T09:49:56.392+0900] {processor.py:157} INFO - Started process (PID=1480) to work on /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:49:56.394+0900] {processor.py:829} INFO - Processing file /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-09-21T09:49:56.395+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:49:56.395+0900] {dagbag.py:539} INFO - Filling up the DagBag from /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:49:56.397+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:49:56.396+0900] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-09-21T09:49:56.397+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:49:56.397+0900] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-09-21T09:49:56.397+0900] {processor.py:841} WARNING - No viable dags retrieved from /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:49:56.402+0900] {processor.py:179} INFO - Processing /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.012 seconds
[2023-09-21T09:50:41.512+0900] {processor.py:157} INFO - Started process (PID=1674) to work on /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:50:41.514+0900] {processor.py:829} INFO - Processing file /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-09-21T09:50:41.514+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:50:41.514+0900] {dagbag.py:539} INFO - Filling up the DagBag from /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:50:41.516+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:50:41.516+0900] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-09-21T09:50:41.516+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:50:41.516+0900] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-09-21T09:50:41.516+0900] {processor.py:841} WARNING - No viable dags retrieved from /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:50:41.522+0900] {processor.py:179} INFO - Processing /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.012 seconds
[2023-09-21T09:51:25.495+0900] {processor.py:157} INFO - Started process (PID=1848) to work on /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:51:25.498+0900] {processor.py:829} INFO - Processing file /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-09-21T09:51:25.498+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:51:25.498+0900] {dagbag.py:539} INFO - Filling up the DagBag from /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:51:25.500+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:51:25.500+0900] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-09-21T09:51:25.500+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:51:25.500+0900] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-09-21T09:51:25.500+0900] {processor.py:841} WARNING - No viable dags retrieved from /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:51:25.506+0900] {processor.py:179} INFO - Processing /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.013 seconds
[2023-09-21T09:52:13.327+0900] {processor.py:157} INFO - Started process (PID=2044) to work on /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:52:13.330+0900] {processor.py:829} INFO - Processing file /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-09-21T09:52:13.330+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:52:13.330+0900] {dagbag.py:539} INFO - Filling up the DagBag from /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:52:13.332+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:52:13.332+0900] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-09-21T09:52:13.332+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:52:13.332+0900] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-09-21T09:52:13.332+0900] {processor.py:841} WARNING - No viable dags retrieved from /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:52:13.338+0900] {processor.py:179} INFO - Processing /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.012 seconds
[2023-09-21T09:52:57.963+0900] {processor.py:157} INFO - Started process (PID=2225) to work on /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:52:57.965+0900] {processor.py:829} INFO - Processing file /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-09-21T09:52:57.965+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:52:57.965+0900] {dagbag.py:539} INFO - Filling up the DagBag from /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:52:57.968+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:52:57.967+0900] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-09-21T09:52:57.968+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:52:57.968+0900] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-09-21T09:52:57.968+0900] {processor.py:841} WARNING - No viable dags retrieved from /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:52:57.974+0900] {processor.py:179} INFO - Processing /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.013 seconds
[2023-09-21T09:53:49.149+0900] {processor.py:157} INFO - Started process (PID=2429) to work on /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:53:49.149+0900] {processor.py:829} INFO - Processing file /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-09-21T09:53:49.150+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:53:49.150+0900] {dagbag.py:539} INFO - Filling up the DagBag from /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:53:49.152+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:53:49.151+0900] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-09-21T09:53:49.152+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:53:49.152+0900] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-09-21T09:53:49.152+0900] {processor.py:841} WARNING - No viable dags retrieved from /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:53:49.158+0900] {processor.py:179} INFO - Processing /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.011 seconds
[2023-09-21T09:54:34.552+0900] {processor.py:157} INFO - Started process (PID=2610) to work on /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:54:34.554+0900] {processor.py:829} INFO - Processing file /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-09-21T09:54:34.555+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:54:34.554+0900] {dagbag.py:539} INFO - Filling up the DagBag from /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:54:34.556+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:54:34.556+0900] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-09-21T09:54:34.556+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:54:34.556+0900] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-09-21T09:54:34.557+0900] {processor.py:841} WARNING - No viable dags retrieved from /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:54:34.563+0900] {processor.py:179} INFO - Processing /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.012 seconds
[2023-09-21T09:55:20.133+0900] {processor.py:157} INFO - Started process (PID=2791) to work on /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:55:20.135+0900] {processor.py:829} INFO - Processing file /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-09-21T09:55:20.135+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:55:20.135+0900] {dagbag.py:539} INFO - Filling up the DagBag from /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:55:20.137+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:55:20.137+0900] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-09-21T09:55:20.137+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:55:20.137+0900] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-09-21T09:55:20.137+0900] {processor.py:841} WARNING - No viable dags retrieved from /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:55:20.143+0900] {processor.py:179} INFO - Processing /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.012 seconds
[2023-09-21T09:56:09.140+0900] {processor.py:157} INFO - Started process (PID=2997) to work on /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:56:09.142+0900] {processor.py:829} INFO - Processing file /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-09-21T09:56:09.142+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:56:09.142+0900] {dagbag.py:539} INFO - Filling up the DagBag from /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:56:09.144+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:56:09.144+0900] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-09-21T09:56:09.145+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:56:09.145+0900] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-09-21T09:56:09.145+0900] {processor.py:841} WARNING - No viable dags retrieved from /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:56:09.150+0900] {processor.py:179} INFO - Processing /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.012 seconds
[2023-09-21T09:56:54.139+0900] {processor.py:157} INFO - Started process (PID=3182) to work on /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:56:54.142+0900] {processor.py:829} INFO - Processing file /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-09-21T09:56:54.142+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:56:54.142+0900] {dagbag.py:539} INFO - Filling up the DagBag from /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:56:54.144+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:56:54.144+0900] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-09-21T09:56:54.144+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:56:54.144+0900] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-09-21T09:56:54.145+0900] {processor.py:841} WARNING - No viable dags retrieved from /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:56:54.150+0900] {processor.py:179} INFO - Processing /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.012 seconds
[2023-09-21T09:57:43.731+0900] {processor.py:157} INFO - Started process (PID=3379) to work on /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:57:43.732+0900] {processor.py:829} INFO - Processing file /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-09-21T09:57:43.733+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:57:43.733+0900] {dagbag.py:539} INFO - Filling up the DagBag from /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:57:43.735+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:57:43.734+0900] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-09-21T09:57:43.735+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:57:43.735+0900] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-09-21T09:57:43.735+0900] {processor.py:841} WARNING - No viable dags retrieved from /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:57:43.741+0900] {processor.py:179} INFO - Processing /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.011 seconds
[2023-09-21T09:58:35.437+0900] {processor.py:157} INFO - Started process (PID=3583) to work on /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:58:35.438+0900] {processor.py:829} INFO - Processing file /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-09-21T09:58:35.439+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:58:35.439+0900] {dagbag.py:539} INFO - Filling up the DagBag from /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:58:35.441+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:58:35.440+0900] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-09-21T09:58:35.441+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:58:35.441+0900] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-09-21T09:58:35.441+0900] {processor.py:841} WARNING - No viable dags retrieved from /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:58:35.447+0900] {processor.py:179} INFO - Processing /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.011 seconds
[2023-09-21T09:59:23.020+0900] {processor.py:157} INFO - Started process (PID=3778) to work on /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:59:23.021+0900] {processor.py:829} INFO - Processing file /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-09-21T09:59:23.022+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:59:23.021+0900] {dagbag.py:539} INFO - Filling up the DagBag from /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:59:23.024+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:59:23.023+0900] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-09-21T09:59:23.024+0900] {logging_mixin.py:151} INFO - [2023-09-21T09:59:23.024+0900] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-09-21T09:59:23.024+0900] {processor.py:841} WARNING - No viable dags retrieved from /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T09:59:23.029+0900] {processor.py:179} INFO - Processing /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.011 seconds
[2023-09-21T10:00:09.246+0900] {processor.py:157} INFO - Started process (PID=3961) to work on /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T10:00:09.249+0900] {processor.py:829} INFO - Processing file /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-09-21T10:00:09.249+0900] {logging_mixin.py:151} INFO - [2023-09-21T10:00:09.249+0900] {dagbag.py:539} INFO - Filling up the DagBag from /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T10:00:09.251+0900] {logging_mixin.py:151} INFO - [2023-09-21T10:00:09.251+0900] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-09-21T10:00:09.251+0900] {logging_mixin.py:151} INFO - [2023-09-21T10:00:09.251+0900] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-09-21T10:00:09.251+0900] {processor.py:841} WARNING - No viable dags retrieved from /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T10:00:09.257+0900] {processor.py:179} INFO - Processing /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.013 seconds
[2023-09-21T10:00:56.780+0900] {processor.py:157} INFO - Started process (PID=4173) to work on /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T10:00:56.782+0900] {processor.py:829} INFO - Processing file /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-09-21T10:00:56.783+0900] {logging_mixin.py:151} INFO - [2023-09-21T10:00:56.783+0900] {dagbag.py:539} INFO - Filling up the DagBag from /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T10:00:56.785+0900] {logging_mixin.py:151} INFO - [2023-09-21T10:00:56.784+0900] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-09-21T10:00:56.785+0900] {logging_mixin.py:151} INFO - [2023-09-21T10:00:56.785+0900] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-09-21T10:00:56.785+0900] {processor.py:841} WARNING - No viable dags retrieved from /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T10:00:56.791+0900] {processor.py:179} INFO - Processing /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.012 seconds
[2023-09-21T10:01:41.788+0900] {processor.py:157} INFO - Started process (PID=4355) to work on /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T10:01:41.790+0900] {processor.py:829} INFO - Processing file /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-09-21T10:01:41.790+0900] {logging_mixin.py:151} INFO - [2023-09-21T10:01:41.790+0900] {dagbag.py:539} INFO - Filling up the DagBag from /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T10:01:41.792+0900] {logging_mixin.py:151} INFO - [2023-09-21T10:01:41.792+0900] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-09-21T10:01:41.792+0900] {logging_mixin.py:151} INFO - [2023-09-21T10:01:41.792+0900] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-09-21T10:01:41.792+0900] {processor.py:841} WARNING - No viable dags retrieved from /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T10:01:41.798+0900] {processor.py:179} INFO - Processing /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.012 seconds
[2023-09-21T10:02:33.062+0900] {processor.py:157} INFO - Started process (PID=4557) to work on /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T10:02:33.063+0900] {processor.py:829} INFO - Processing file /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-09-21T10:02:33.063+0900] {logging_mixin.py:151} INFO - [2023-09-21T10:02:33.063+0900] {dagbag.py:539} INFO - Filling up the DagBag from /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T10:02:33.065+0900] {logging_mixin.py:151} INFO - [2023-09-21T10:02:33.064+0900] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-09-21T10:02:33.065+0900] {logging_mixin.py:151} INFO - [2023-09-21T10:02:33.065+0900] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-09-21T10:02:33.065+0900] {processor.py:841} WARNING - No viable dags retrieved from /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T10:02:33.071+0900] {processor.py:179} INFO - Processing /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.011 seconds
[2023-09-21T10:03:19.042+0900] {processor.py:157} INFO - Started process (PID=4739) to work on /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T10:03:19.043+0900] {processor.py:829} INFO - Processing file /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-09-21T10:03:19.044+0900] {logging_mixin.py:151} INFO - [2023-09-21T10:03:19.043+0900] {dagbag.py:539} INFO - Filling up the DagBag from /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T10:03:19.045+0900] {logging_mixin.py:151} INFO - [2023-09-21T10:03:19.045+0900] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-09-21T10:03:19.045+0900] {logging_mixin.py:151} INFO - [2023-09-21T10:03:19.045+0900] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-09-21T10:03:19.045+0900] {processor.py:841} WARNING - No viable dags retrieved from /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T10:03:19.051+0900] {processor.py:179} INFO - Processing /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.011 seconds
[2023-09-21T10:04:08.536+0900] {processor.py:157} INFO - Started process (PID=4936) to work on /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T10:04:08.538+0900] {processor.py:829} INFO - Processing file /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-09-21T10:04:08.538+0900] {logging_mixin.py:151} INFO - [2023-09-21T10:04:08.538+0900] {dagbag.py:539} INFO - Filling up the DagBag from /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T10:04:08.540+0900] {logging_mixin.py:151} INFO - [2023-09-21T10:04:08.540+0900] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-09-21T10:04:08.540+0900] {logging_mixin.py:151} INFO - [2023-09-21T10:04:08.540+0900] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-09-21T10:04:08.540+0900] {processor.py:841} WARNING - No viable dags retrieved from /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T10:04:08.546+0900] {processor.py:179} INFO - Processing /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.012 seconds
[2023-09-21T10:04:57.268+0900] {processor.py:157} INFO - Started process (PID=5135) to work on /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T10:04:57.269+0900] {processor.py:829} INFO - Processing file /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-09-21T10:04:57.270+0900] {logging_mixin.py:151} INFO - [2023-09-21T10:04:57.270+0900] {dagbag.py:539} INFO - Filling up the DagBag from /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T10:04:57.272+0900] {logging_mixin.py:151} INFO - [2023-09-21T10:04:57.272+0900] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-09-21T10:04:57.272+0900] {logging_mixin.py:151} INFO - [2023-09-21T10:04:57.272+0900] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-09-21T10:04:57.272+0900] {processor.py:841} WARNING - No viable dags retrieved from /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T10:04:57.278+0900] {processor.py:179} INFO - Processing /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.012 seconds
[2023-09-21T10:05:43.040+0900] {processor.py:157} INFO - Started process (PID=5335) to work on /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T10:05:43.042+0900] {processor.py:829} INFO - Processing file /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-09-21T10:05:43.042+0900] {logging_mixin.py:151} INFO - [2023-09-21T10:05:43.042+0900] {dagbag.py:539} INFO - Filling up the DagBag from /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T10:05:43.044+0900] {logging_mixin.py:151} INFO - [2023-09-21T10:05:43.044+0900] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-09-21T10:05:43.044+0900] {logging_mixin.py:151} INFO - [2023-09-21T10:05:43.044+0900] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-09-21T10:05:43.044+0900] {processor.py:841} WARNING - No viable dags retrieved from /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T10:05:43.050+0900] {processor.py:179} INFO - Processing /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.012 seconds
[2023-09-21T10:06:32.429+0900] {processor.py:157} INFO - Started process (PID=5533) to work on /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T10:06:32.431+0900] {processor.py:829} INFO - Processing file /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-09-21T10:06:32.432+0900] {logging_mixin.py:151} INFO - [2023-09-21T10:06:32.432+0900] {dagbag.py:539} INFO - Filling up the DagBag from /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T10:06:32.434+0900] {logging_mixin.py:151} INFO - [2023-09-21T10:06:32.433+0900] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-09-21T10:06:32.434+0900] {logging_mixin.py:151} INFO - [2023-09-21T10:06:32.434+0900] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-09-21T10:06:32.434+0900] {processor.py:841} WARNING - No viable dags retrieved from /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T10:06:32.439+0900] {processor.py:179} INFO - Processing /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.012 seconds
[2023-09-21T10:07:24.228+0900] {processor.py:157} INFO - Started process (PID=5737) to work on /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T10:07:24.230+0900] {processor.py:829} INFO - Processing file /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-09-21T10:07:24.231+0900] {logging_mixin.py:151} INFO - [2023-09-21T10:07:24.230+0900] {dagbag.py:539} INFO - Filling up the DagBag from /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T10:07:24.233+0900] {logging_mixin.py:151} INFO - [2023-09-21T10:07:24.232+0900] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-09-21T10:07:24.233+0900] {logging_mixin.py:151} INFO - [2023-09-21T10:07:24.233+0900] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-09-21T10:07:24.233+0900] {processor.py:841} WARNING - No viable dags retrieved from /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T10:07:24.239+0900] {processor.py:179} INFO - Processing /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.012 seconds
[2023-09-21T10:08:07.640+0900] {processor.py:157} INFO - Started process (PID=5912) to work on /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T10:08:07.642+0900] {processor.py:829} INFO - Processing file /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-09-21T10:08:07.643+0900] {logging_mixin.py:151} INFO - [2023-09-21T10:08:07.643+0900] {dagbag.py:539} INFO - Filling up the DagBag from /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T10:08:07.645+0900] {logging_mixin.py:151} INFO - [2023-09-21T10:08:07.645+0900] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-09-21T10:08:07.645+0900] {logging_mixin.py:151} INFO - [2023-09-21T10:08:07.645+0900] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-09-21T10:08:07.645+0900] {processor.py:841} WARNING - No viable dags retrieved from /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T10:08:07.651+0900] {processor.py:179} INFO - Processing /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.012 seconds
[2023-09-21T10:08:51.023+0900] {processor.py:157} INFO - Started process (PID=6086) to work on /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T10:08:51.025+0900] {processor.py:829} INFO - Processing file /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-09-21T10:08:51.025+0900] {logging_mixin.py:151} INFO - [2023-09-21T10:08:51.025+0900] {dagbag.py:539} INFO - Filling up the DagBag from /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T10:08:51.028+0900] {logging_mixin.py:151} INFO - [2023-09-21T10:08:51.027+0900] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-09-21T10:08:51.028+0900] {logging_mixin.py:151} INFO - [2023-09-21T10:08:51.028+0900] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-09-21T10:08:51.028+0900] {processor.py:841} WARNING - No viable dags retrieved from /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T10:08:51.033+0900] {processor.py:179} INFO - Processing /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.012 seconds
[2023-09-21T10:09:39.165+0900] {processor.py:157} INFO - Started process (PID=6282) to work on /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T10:09:39.167+0900] {processor.py:829} INFO - Processing file /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-09-21T10:09:39.167+0900] {logging_mixin.py:151} INFO - [2023-09-21T10:09:39.167+0900] {dagbag.py:539} INFO - Filling up the DagBag from /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T10:09:39.169+0900] {logging_mixin.py:151} INFO - [2023-09-21T10:09:39.169+0900] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-09-21T10:09:39.169+0900] {logging_mixin.py:151} INFO - [2023-09-21T10:09:39.169+0900] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-09-21T10:09:39.169+0900] {processor.py:841} WARNING - No viable dags retrieved from /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T10:09:39.175+0900] {processor.py:179} INFO - Processing /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.012 seconds
[2023-09-21T10:10:23.440+0900] {processor.py:157} INFO - Started process (PID=6461) to work on /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T10:10:23.442+0900] {processor.py:829} INFO - Processing file /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-09-21T10:10:23.443+0900] {logging_mixin.py:151} INFO - [2023-09-21T10:10:23.442+0900] {dagbag.py:539} INFO - Filling up the DagBag from /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T10:10:23.444+0900] {logging_mixin.py:151} INFO - [2023-09-21T10:10:23.444+0900] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-09-21T10:10:23.444+0900] {logging_mixin.py:151} INFO - [2023-09-21T10:10:23.444+0900] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-09-21T10:10:23.445+0900] {processor.py:841} WARNING - No viable dags retrieved from /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T10:10:23.450+0900] {processor.py:179} INFO - Processing /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.012 seconds
[2023-09-21T10:11:09.991+0900] {processor.py:157} INFO - Started process (PID=6655) to work on /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T10:11:09.992+0900] {processor.py:829} INFO - Processing file /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-09-21T10:11:09.993+0900] {logging_mixin.py:151} INFO - [2023-09-21T10:11:09.992+0900] {dagbag.py:539} INFO - Filling up the DagBag from /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T10:11:09.995+0900] {logging_mixin.py:151} INFO - [2023-09-21T10:11:09.994+0900] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-09-21T10:11:09.995+0900] {logging_mixin.py:151} INFO - [2023-09-21T10:11:09.995+0900] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-09-21T10:11:09.995+0900] {processor.py:841} WARNING - No viable dags retrieved from /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T10:11:10.000+0900] {processor.py:179} INFO - Processing /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.011 seconds
[2023-09-21T10:11:55.516+0900] {processor.py:157} INFO - Started process (PID=6843) to work on /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T10:11:55.516+0900] {processor.py:829} INFO - Processing file /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-09-21T10:11:55.517+0900] {logging_mixin.py:151} INFO - [2023-09-21T10:11:55.517+0900] {dagbag.py:539} INFO - Filling up the DagBag from /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T10:11:55.519+0900] {logging_mixin.py:151} INFO - [2023-09-21T10:11:55.518+0900] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-09-21T10:11:55.519+0900] {logging_mixin.py:151} INFO - [2023-09-21T10:11:55.519+0900] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-09-21T10:11:55.519+0900] {processor.py:841} WARNING - No viable dags retrieved from /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T10:11:55.524+0900] {processor.py:179} INFO - Processing /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.010 seconds
[2023-09-21T10:12:40.784+0900] {processor.py:157} INFO - Started process (PID=7025) to work on /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T10:12:40.785+0900] {processor.py:829} INFO - Processing file /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-09-21T10:12:40.785+0900] {logging_mixin.py:151} INFO - [2023-09-21T10:12:40.785+0900] {dagbag.py:539} INFO - Filling up the DagBag from /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T10:12:40.787+0900] {logging_mixin.py:151} INFO - [2023-09-21T10:12:40.787+0900] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-09-21T10:12:40.787+0900] {logging_mixin.py:151} INFO - [2023-09-21T10:12:40.787+0900] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-09-21T10:12:40.787+0900] {processor.py:841} WARNING - No viable dags retrieved from /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T10:12:40.793+0900] {processor.py:179} INFO - Processing /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.011 seconds
[2023-09-21T10:13:23.042+0900] {processor.py:157} INFO - Started process (PID=7190) to work on /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T10:13:23.043+0900] {processor.py:829} INFO - Processing file /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-09-21T10:13:23.044+0900] {logging_mixin.py:151} INFO - [2023-09-21T10:13:23.044+0900] {dagbag.py:539} INFO - Filling up the DagBag from /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T10:13:23.046+0900] {logging_mixin.py:151} INFO - [2023-09-21T10:13:23.045+0900] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-09-21T10:13:23.046+0900] {logging_mixin.py:151} INFO - [2023-09-21T10:13:23.046+0900] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-09-21T10:13:23.046+0900] {processor.py:841} WARNING - No viable dags retrieved from /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T10:13:23.051+0900] {processor.py:179} INFO - Processing /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.010 seconds
[2023-09-21T10:14:11.543+0900] {processor.py:157} INFO - Started process (PID=7387) to work on /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T10:14:11.544+0900] {processor.py:829} INFO - Processing file /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-09-21T10:14:11.545+0900] {logging_mixin.py:151} INFO - [2023-09-21T10:14:11.545+0900] {dagbag.py:539} INFO - Filling up the DagBag from /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T10:14:11.547+0900] {logging_mixin.py:151} INFO - [2023-09-21T10:14:11.546+0900] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-09-21T10:14:11.547+0900] {logging_mixin.py:151} INFO - [2023-09-21T10:14:11.547+0900] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-09-21T10:14:11.547+0900] {processor.py:841} WARNING - No viable dags retrieved from /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T10:14:11.552+0900] {processor.py:179} INFO - Processing /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.011 seconds
[2023-09-21T10:14:55.823+0900] {processor.py:157} INFO - Started process (PID=7568) to work on /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T10:14:55.824+0900] {processor.py:829} INFO - Processing file /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-09-21T10:14:55.824+0900] {logging_mixin.py:151} INFO - [2023-09-21T10:14:55.824+0900] {dagbag.py:539} INFO - Filling up the DagBag from /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T10:14:55.826+0900] {logging_mixin.py:151} INFO - [2023-09-21T10:14:55.825+0900] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-09-21T10:14:55.826+0900] {logging_mixin.py:151} INFO - [2023-09-21T10:14:55.826+0900] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-09-21T10:14:55.826+0900] {processor.py:841} WARNING - No viable dags retrieved from /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T10:14:55.831+0900] {processor.py:179} INFO - Processing /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.010 seconds
[2023-09-21T10:15:40.483+0900] {processor.py:157} INFO - Started process (PID=7764) to work on /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T10:15:40.484+0900] {processor.py:829} INFO - Processing file /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-09-21T10:15:40.485+0900] {logging_mixin.py:151} INFO - [2023-09-21T10:15:40.484+0900] {dagbag.py:539} INFO - Filling up the DagBag from /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T10:15:40.487+0900] {logging_mixin.py:151} INFO - [2023-09-21T10:15:40.486+0900] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-09-21T10:15:40.487+0900] {logging_mixin.py:151} INFO - [2023-09-21T10:15:40.487+0900] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-09-21T10:15:40.487+0900] {processor.py:841} WARNING - No viable dags retrieved from /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T10:15:40.492+0900] {processor.py:179} INFO - Processing /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.011 seconds
[2023-09-21T10:16:27.767+0900] {processor.py:157} INFO - Started process (PID=7952) to work on /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T10:16:27.768+0900] {processor.py:829} INFO - Processing file /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-09-21T10:16:27.768+0900] {logging_mixin.py:151} INFO - [2023-09-21T10:16:27.768+0900] {dagbag.py:539} INFO - Filling up the DagBag from /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T10:16:27.770+0900] {logging_mixin.py:151} INFO - [2023-09-21T10:16:27.770+0900] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-09-21T10:16:27.770+0900] {logging_mixin.py:151} INFO - [2023-09-21T10:16:27.770+0900] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-09-21T10:16:27.771+0900] {processor.py:841} WARNING - No viable dags retrieved from /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T10:16:27.776+0900] {processor.py:179} INFO - Processing /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.011 seconds
[2023-09-21T10:17:18.006+0900] {processor.py:157} INFO - Started process (PID=8149) to work on /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T10:17:18.008+0900] {processor.py:829} INFO - Processing file /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-09-21T10:17:18.008+0900] {logging_mixin.py:151} INFO - [2023-09-21T10:17:18.008+0900] {dagbag.py:539} INFO - Filling up the DagBag from /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T10:17:18.010+0900] {logging_mixin.py:151} INFO - [2023-09-21T10:17:18.010+0900] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-09-21T10:17:18.010+0900] {logging_mixin.py:151} INFO - [2023-09-21T10:17:18.010+0900] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-09-21T10:17:18.010+0900] {processor.py:841} WARNING - No viable dags retrieved from /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T10:17:18.016+0900] {processor.py:179} INFO - Processing /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.012 seconds
[2023-09-21T10:18:15.652+0900] {processor.py:157} INFO - Started process (PID=8380) to work on /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T10:18:15.655+0900] {processor.py:829} INFO - Processing file /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-09-21T10:18:15.655+0900] {logging_mixin.py:151} INFO - [2023-09-21T10:18:15.655+0900] {dagbag.py:539} INFO - Filling up the DagBag from /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T10:18:15.657+0900] {logging_mixin.py:151} INFO - [2023-09-21T10:18:15.657+0900] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-09-21T10:18:15.657+0900] {logging_mixin.py:151} INFO - [2023-09-21T10:18:15.657+0900] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-09-21T10:18:15.657+0900] {processor.py:841} WARNING - No viable dags retrieved from /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T10:18:15.662+0900] {processor.py:179} INFO - Processing /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.012 seconds
[2023-09-21T10:19:03.026+0900] {processor.py:157} INFO - Started process (PID=8575) to work on /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T10:19:03.028+0900] {processor.py:829} INFO - Processing file /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-09-21T10:19:03.029+0900] {logging_mixin.py:151} INFO - [2023-09-21T10:19:03.029+0900] {dagbag.py:539} INFO - Filling up the DagBag from /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T10:19:03.031+0900] {logging_mixin.py:151} INFO - [2023-09-21T10:19:03.030+0900] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-09-21T10:19:03.031+0900] {logging_mixin.py:151} INFO - [2023-09-21T10:19:03.031+0900] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-09-21T10:19:03.031+0900] {processor.py:841} WARNING - No viable dags retrieved from /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T10:19:03.037+0900] {processor.py:179} INFO - Processing /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.012 seconds
[2023-09-21T10:19:54.829+0900] {processor.py:157} INFO - Started process (PID=8779) to work on /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T10:19:54.832+0900] {processor.py:829} INFO - Processing file /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-09-21T10:19:54.832+0900] {logging_mixin.py:151} INFO - [2023-09-21T10:19:54.832+0900] {dagbag.py:539} INFO - Filling up the DagBag from /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T10:19:54.834+0900] {logging_mixin.py:151} INFO - [2023-09-21T10:19:54.834+0900] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-09-21T10:19:54.834+0900] {logging_mixin.py:151} INFO - [2023-09-21T10:19:54.834+0900] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-09-21T10:19:54.834+0900] {processor.py:841} WARNING - No viable dags retrieved from /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T10:19:54.839+0900] {processor.py:179} INFO - Processing /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.012 seconds
[2023-09-21T10:20:38.226+0900] {processor.py:157} INFO - Started process (PID=8966) to work on /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T10:20:38.228+0900] {processor.py:829} INFO - Processing file /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-09-21T10:20:38.229+0900] {logging_mixin.py:151} INFO - [2023-09-21T10:20:38.228+0900] {dagbag.py:539} INFO - Filling up the DagBag from /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T10:20:38.231+0900] {logging_mixin.py:151} INFO - [2023-09-21T10:20:38.231+0900] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-09-21T10:20:38.231+0900] {logging_mixin.py:151} INFO - [2023-09-21T10:20:38.231+0900] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-09-21T10:20:38.231+0900] {processor.py:841} WARNING - No viable dags retrieved from /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T10:20:38.236+0900] {processor.py:179} INFO - Processing /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.012 seconds
[2023-09-21T10:21:22.583+0900] {processor.py:157} INFO - Started process (PID=9440) to work on /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T10:21:22.585+0900] {processor.py:829} INFO - Processing file /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-09-21T10:21:22.585+0900] {logging_mixin.py:151} INFO - [2023-09-21T10:21:22.585+0900] {dagbag.py:539} INFO - Filling up the DagBag from /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T10:21:22.587+0900] {logging_mixin.py:151} INFO - [2023-09-21T10:21:22.587+0900] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-09-21T10:21:22.587+0900] {logging_mixin.py:151} INFO - [2023-09-21T10:21:22.587+0900] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-09-21T10:21:22.588+0900] {processor.py:841} WARNING - No viable dags retrieved from /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-09-21T10:21:22.593+0900] {processor.py:179} INFO - Processing /home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.012 seconds
